# docker-compose.yml
version: '3.8'
services:
 # Application
  app:
      build:
          context: .
          dockerfile: app.dockerfile
      working_dir: /var/www
      environment:
        DATABASE_URL: postgres://postgres:postgres@db:5432/sample-web-1
        REDIS_URL: redis://redis:6379
      volumes:
          - ./:/var/www
      depends_on:
          - "db"
    # Web Server
  web:
        build:
            context: .
            dockerfile: web.dockerfile
        working_dir: /var/www
        volumes:
            - ./:/var/www
        depends_on:
            - "app"
        ports:
            - 80:80  
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypassword
      POSTGRES_DB: mydb
    volumes:
       - ./data:/var/lib/postgresql/data
  redis:
    image: redis
    restart: unless-stopped